
var detectableWithVB=false;$(document).ready(function(){var txtJobSearchBoxVal=$(".TxtJobSearchBox").val();var txtJobSearchBox="";if(txtJobSearchBoxVal!=undefined){txtJobSearchBox=txtJobSearchBoxVal.replace("'","");if(txtJobSearchBox!=defaultKeyword){txtJobSearchBox=txtJobSearchBoxVal;}
if($(".containerSearchBoxRow").html()!=null){$(".TxtJobSearchBox").focus(function(){if(txtJobSearchBox==defaultKeyword){$(".TxtJobSearchBox").val('');}
ChangeToNormalCss()});if(txtJobSearchBox!=defaultKeyword){ChangeToNormalCss()}}}
if($(".containerSearchBoxRow").html()!=null){$(".jobSearchBoxButton").click(function(){if($.cookie("savefilters")!=null){deleteCookie("savefilters");}});}});function setCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function deleteCookie(name){setCookie(name,"",-1);}
function ChangeToNormalCss(){$(".TxtJobSearchBox").css('color','#000000');$(".TxtJobSearchBox").css('font-style','normal');}
function DetectBrowser(){var pluginFound=DetectPlugin("Shockwave","Flash");if(!pluginFound&&detectableWithVB){pluginFound=detectActiveXControl('ShockwaveFlash.ShockwaveFlash.1');}
if(pluginFound==false){$("#HomePageMainFlashContent").hide();$("img[id$='HomePageMainImage']").show();}
else{$(".mboxDefault").css("visibility","visible");$("#HomePageMainFlashContent").hide();$("#HomePageMainFlashContent").show();}}
function DetectPlugin(){var daPlugins=DetectPlugin.arguments;var pluginFound=false;if(navigator.plugins&&navigator.plugins.length>0){var pluginsArrayLength=navigator.plugins.length;for(pluginsArrayCounter=0;pluginsArrayCounter<pluginsArrayLength;pluginsArrayCounter++){var numFound=0;for(namesCounter=0;namesCounter<daPlugins.length;namesCounter++){if((navigator.plugins[pluginsArrayCounter].name.indexOf(daPlugins[namesCounter])>=0)||(navigator.plugins[pluginsArrayCounter].description.indexOf(daPlugins[namesCounter])>=0)){numFound++;}}
if(numFound==daPlugins.length){pluginFound=true;break;}}}
return pluginFound;}
if((navigator.userAgent.indexOf('MSIE')!=-1)&&(navigator.userAgent.indexOf('Win')!=-1)){document.writeln('<script language="VBscript">');document.writeln('\'do a one-time test for a version of VBScript that can handle this code');document.writeln('detectableWithVB = False');document.writeln('If ScriptEngineMajorVersion >= 2 then');document.writeln('  detectableWithVB = True');document.writeln('End If');document.writeln('\'this next function will detect most plugins');document.writeln('Function detectActiveXControl(activeXControlName)');document.writeln('  on error resume next');document.writeln('  detectActiveXControl = False');document.writeln('  If detectableWithVB Then');document.writeln('     detectActiveXControl = IsObject(CreateObject(activeXControlName))');document.writeln('  End If');document.writeln('End Function');document.writeln('</scr'+'ipt>');}
function InitializeBehavior(Behavior,DelayTime,Community){var $jsautoScrollBehavior=Behavior;var $jsautoScrollDelayTime=DelayTime;var $reverseButton='/Style Library/Accenture/Images/Home_Reverse_Button.png';var $forwardButton='/Style Library/Accenture/Images/Home_Forward_Button.png';if(Community=="true"){var $reverseButton='/Style Library/Accenture/Images/blue_button_left.jpg';var $forwardButton='/Style Library/Accenture/Images/blue_button_right.jpg';}
if($jsautoScrollBehavior=="DoNotRotate"){stepcarousel.setup({galleryid:'mygallery',beltclass:'belt',panelclass:'panel',autostep:{enable:false,moveby:1,pause:$jsautoScrollDelayTime,mode:'NoRotate'},panelbehavior:{speed:500,wraparound:false,persist:true},defaultbuttons:{enable:true,moveby:1,leftnav:[$reverseButton,-30,156],rightnav:[$forwardButton,5,156]},statusvars:['statusA','statusB','statusC'],contenttype:['inline']})}
else if($jsautoScrollBehavior=="RotateOnce"){stepcarousel.setup({galleryid:'mygallery',beltclass:'belt',panelclass:'panel',autostep:{enable:true,moveby:1,pause:$jsautoScrollDelayTime,mode:'SingleRotate'},panelbehavior:{speed:500,wraparound:true,persist:true},defaultbuttons:{enable:true,moveby:1,leftnav:[$reverseButton,-30,156],rightnav:[$forwardButton,5,156]},statusvars:['statusA','statusB','statusC'],contenttype:['inline']})}
else{stepcarousel.setup({galleryid:'mygallery',beltclass:'belt',panelclass:'panel',autostep:{enable:true,moveby:1,pause:$jsautoScrollDelayTime,mode:'MultiRotate'},panelbehavior:{speed:500,wraparound:true,persist:true},defaultbuttons:{enable:true,moveby:1,leftnav:[$reverseButton,-30,156],rightnav:[$forwardButton,5,156]},statusvars:['statusA','statusB','statusC'],contenttype:['inline']})}}
function DisplayImageAfterFlash(){$("#homepage-maincontent").hide();$("#homepage-maincontent-image").show().attr("display","inline");DisplayPrimaryNav();}
function DisplayPrimaryNav(){DisplayFeaturedSection();}
function DisplayFeaturedSection(){$("#FeaturedSectionContent").attr("class","feature-section-parent");}
function SetSegmentedContentStyle(){var imgSrc=$("#segmented-image img").attr("src");$(".segmented-content-summary-noimage").removeClass("segmented-content-summary-noimage");$(".segmented-content-image-notvisble").removeClass("segmented-content-image-notvisble");$(".segment-description-noimage").removeClass("segment-description-noimage");if(imgSrc!==undefined&&imgSrc.toLowerCase()==="/_layouts/images/blank.gif"){$(".segment-image").addClass("segmented-content-image-notvisble");$(".segment-summary").addClass("segmented-content-summary-noimage");$(".segment-description").addClass("segment-description-noimage");}}
function HomePageAnchorToggler(){$(document).ready(function(){$("a").attr("target",function(){var regexpcheckurl=/(ftp|http|https)?(:\/\/\w+)?(\-)?(\w+)?.accenture.com(\/\w+)?/;if(regexpcheckurl.test(this.href))
return"_self";return"_new";});$("#paging-1").attr("class","active-page");SetSegmentedContentStyle()
$('#paging-1').click(function(e){if(!$('#paging-1').hasClass('active-page')){$("#segmented-content-functionalarea").hide();$("#segmented-content-industry").hide();$("#segmented-content-company").show().attr("display","inline");if(typeof window.s_code!="undefined"&&window.s_code!=null){TrackProductsImpression(RetrieveProductsImpression($('div.segmented-content-parent')));}
if(e.preventDefault()){e.preventDefault();}
else{e.returnValue=false;}
$("#paging-1").attr("class","active-page");$("#paging-2").attr("class","segmented-page");$("#paging-3").attr("class","segmented-page");SetSegmentedContentStyle()}});$('#paging-2').click(function(e){if(!$('#paging-2').hasClass('active-page')){$("#segmented-content-company").hide();$("#segmented-content-functionalarea").hide();$("#segmented-content-industry").show().attr("display","inline");if(typeof window.s_code!="undefined"&&window.s_code!=null){TrackProductsImpression(RetrieveProductsImpression($('div.segmented-content-parent')));}
if(e.preventDefault()){e.preventDefault();}
else{e.returnValue=false;}
$("#paging-2").attr("class","active-page");$("#paging-1").attr("class","segmented-page");$("#paging-3").attr("class","segmented-page");SetSegmentedContentStyle()}});$('#paging-3').click(function(e){if(!$('#paging-3').hasClass('active-page')){$("#segmented-content-company").hide();$("#segmented-content-industry").hide();$("#segmented-content-functionalarea").show().attr("display","inline");if(typeof window.s_code!="undefined"&&window.s_code!=null){TrackProductsImpression(RetrieveProductsImpression($('div.segmented-content-parent')));}
if(e.preventDefault()){e.preventDefault();}
else{e.returnValue=false;}
$("#paging-3").attr("class","active-page");$("#paging-1").attr("class","segmented-page");$("#paging-2").attr("class","segmented-page");SetSegmentedContentStyle()}});});}